language: python
python:
  - "3.8"

env: 
  - AWS_DEFAULT_REGION=sa-east-1

jobs:

  include:

  - stage: Run Tests
    install:
      - pip3 install -r requirements.txt

    script: 
      - pwd
      - pip3 install -e .
      - pytest

  - stage: Build Docker Image
    if: branch != master
    script:
      - docker build -t stockpredictions-api .
      - docker images
      - docker login
      - docker tag stockpredictions-api stockpredictions-api
  
  - stage: Build and Push Docker Image
    if: branch = master
    script:
      - echo "$ECR_PASSWORD" | docker login -u "$ECR_USERNAME" --password-stdin 012664762550.dkr.ecr.sa-east-1.amazonaws.com
      - docker build -t stockpredictions-api .
      - docker images
      - docker tag stockpredictions-api:latest 012664762550.dkr.ecr.sa-east-1.amazonaws.com/stock-prediction-api:latest
      - docker push 012664762550.dkr.ecr.sa-east-1.amazonaws.com/stock-prediction-api:latest

