language: python
python:
  - "3.8"

env: 
  - AWS_DEFAULT_REGION=sa-east-1

jobs:

  include:

  - stage: Run Tests
    install:
      - pip3 install -r requirements.txt

    script: 
      - pwd
      - pip3 install -e .
      - pytest

  - stage: Build Docker Image
    if: branch != master
    script:
      - docker build -t stockpredictions-api:latest .
      