language: python
python:
  - "3.8"

branches:
  only:
  - master
  - develop

jobs:

  include:
  - stage: Run Tests
    install:
      - pip3 install -r requirements.txt

    script: 
      - pwd
      - pip3 install -e .
      - pytest

  - stage: Build Docker Image
    if: branch != master
    script:
      - docker build -t stockpredictions-api .
      - docker images
      - docker tag stockpredictions-api stockpredictions-api
  
  - stage: Build and Push Docker Image
    if: branch = master
    script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker build -t stockpredictions-api .
      - docker images
      - docker tag stockpredictions-api $DOCKER_USERNAME/stockpredictions-api
      - docker push $DOCKER_USERNAME/stockpredictions-api